"""bnos build CLI — 注入运行时驱动引擎到 BNOS 项目。"""

from __future__ import annotations

import argparse
import json
import shutil
import sys
from pathlib import Path

from bnos_runtime.logger import logger
from bnos_runtime.pipeline_generator import generate_pipeline, validate_pipeline


# ── 白名单：--clean 可删除的文件/目录 ──────────────────────────
CLEAN_TARGETS: list[str] = [
    "bnos_runtime",
    "pipeline.json",
    "run.sh",
    "run.bat",
    "requirements.txt",
    "Dockerfile",
    "docker-compose.yml",
    ".dockerignore",
]

# ── 引擎核心文件清单（inject_runtime_engine 使用） ──────────────
CORE_ENGINE_FILES: list[str] = [
    "__init__.py",
    "engine.py",
    "standalone_runner.py",
    "composite_runner.py",
    "orchestrator.py",
    "pipeline_loader.py",
    "pipeline_generator.py",
    "venv_resolver.py",
    "logger.py",
    "resource_limit.py",
    "build_cli.py",
]


# ──────────────────────────────────────────────
# 引擎注入
# ──────────────────────────────────────────────


def inject_runtime_engine(runtime_dir: Path) -> None:
    """从当前 bnos_runtime 包复制核心模块到目标目录。"""
    import bnos_runtime as pkg

    template_dir = Path(pkg.__file__).parent
    runtime_dir.mkdir(parents=True, exist_ok=True)

    count = 0
    for filename in CORE_ENGINE_FILES:
        src = template_dir / filename
        if not src.exists():
            logger.warning("Engine template '%s' not found, skipping", filename)
            continue
        dst = runtime_dir / filename
        shutil.copy2(src, dst)
        count += 1

    logger.info("Engine injected: %d modules from %s", count, template_dir)


# ──────────────────────────────────────────────
# 启动脚本生成
# ──────────────────────────────────────────────


def generate_run_scripts(project_root: Path) -> None:
    """生成 run.sh 和 run.bat 启动脚本。"""
    # run.sh (Linux/macOS)
    sh_path = project_root / "run.sh"
    sh_content = """#!/usr/bin/env bash
# BNOS Pipeline Runner — 自动生成的启动脚本
# 使用: bash run.sh
set -e
cd "$(dirname "$0")"
python -m bnos_runtime.engine pipeline.json
"""
    sh_path.write_text(sh_content, encoding="utf-8")
    sh_path.chmod(0o755)

    # run.bat (Windows)
    bat_path = project_root / "run.bat"
    bat_content = """@echo off
REM BNOS Pipeline Runner — 自动生成的启动脚本
REM 使用: run.bat
cd /d "%~dp0"
python -m bnos_runtime.engine pipeline.json
pause
"""
    bat_path.write_text(bat_content, encoding="utf-8")


# ──────────────────────────────────────────────
# 依赖扫描
# ──────────────────────────────────────────────


def scan_requirements(project_root: Path, nodes_def: dict) -> set[str]:
    """扫描所有节点的依赖，输出不含 PySide6 的依赖清单。"""
    reqs: set[str] = set()

    for node_name, nd in nodes_def.items():
        # 检查节点 dir 或 venv 中的 requirements.txt
        node_path = project_root / nd["path"]
        req_file = node_path / "requirements.txt"
        if req_file.exists():
            for line in req_file.read_text(encoding="utf-8").splitlines():
                line = line.strip()
                if line and not line.startswith("#") and not line.startswith("-"):
                    # 排除 PySide6 及其变体
                    if "pyside6" not in line.lower():
                        reqs.add(line)

        # 检查 venv 目录
        venv_dir = node_path / ".venv"
        if not venv_dir.exists() and nd.get("venv"):
            venv_dir = project_root / nd["venv"]

    # 确保运行时必备依赖
    reqs.add("psutil>=6.0.0")

    return reqs


# ──────────────────────────────────────────────
# 复合节点 orchestrator 生成
# ──────────────────────────────────────────────


def generate_orchestrator(orch_path: Path, node_def: dict, project_root: Path) -> str:
    """为复合节点生成 orchestrator.py。

    使用现有的 CompositeNode.generate_orchestrator() 或模板渲染。
    """
    comp_id = orch_path.parent.name

    # 优先通过现有模板生成
    try:
        from ui.core.node.composite_orchestrator import render_orchestrator_script  # type: ignore[import-untyped]

        source = render_orchestrator_script(comp_id)
    except ImportError:
        # 兜底：使用简单的 orchestrator 模板
        source = _generate_orchestrator_fallback(comp_id, node_def)

    orch_path.parent.mkdir(parents=True, exist_ok=True)
    orch_path.write_text(source, encoding="utf-8")
    return source


def _generate_orchestrator_fallback(comp_id: str, node_def: dict) -> str:
    """生成 orchestrator.py 的兜底实现。"""
    sub_nodes = list(node_def.get("sub_nodes", {}).keys())
    internal_edges = node_def.get("internal_edges", [])

    lines = [
        f'"""Auto-generated by bnos build — do not edit manually"""',
        f"#",
        f"# 复合节点: {comp_id}",
        f"# 子节点:   {' → '.join(sub_nodes)}",
        f"# 生成时间: 自动生成",
        f"#",
    ]

    # 生成 import 语句
    module_path = f"nodes.{comp_id}.sub_nodes"
    for sn in sub_nodes:
        lines.append(f"from {module_path}.{sn}.main import process as {sn}_process")

    # 子节点列表常量
    sub_nodes_quoted = [f'"{sn}"' for sn in sub_nodes]
    lines.append(f"\nSUB_NODES = [{', '.join(sub_nodes_quoted)}]")

    # 生成拓扑排序常量
    lines.extend([
        "",
        "INTERNAL_EDGES = [",
    ])
    for edge in internal_edges:
        lines.append(f'    ("{edge["from"]}", "{edge["to"]}"),')
    lines.append("]")

    # 生成 main 函数
    lines.extend([
        "",
        "",
        "def main():",
        "    ctx = {}",
        "    order = _topo_sort()",
        "    for name in order:",
        f"        inp = ctx.get(name, {{}})",
        f"        print(f'[ORCH] Running {{name}}...')",
        f"        out = globals()[f'{{name}}_process'](inp)",
        f"        ctx[name] = out",
        f"    print('[ORCH] Composite node complete.')",
        "",
        "",
        "def _topo_sort():",
        "    from collections import defaultdict, deque",
        "    in_degree = {n: 0 for n in SUB_NODES}",
        "    children = defaultdict(list)",
        '    for src, tgt in INTERNAL_EDGES:',
        "        in_degree[tgt] += 1",
        "        children[src].append(tgt)",
        "    queue = deque(n for n, d in in_degree.items() if d == 0)",
        "    order = []",
        "    while queue:",
        "        n = queue.popleft()",
        "        order.append(n)",
        "        for c in children[n]:",
        "            in_degree[c] -= 1",
        "            if in_degree[c] == 0:",
        "                queue.append(c)",
        "    return order",
        "",
        "",
        'if __name__ == "__main__":',
        "    main()",
    ])

    return "\n".join(lines)


# ──────────────────────────────────────────────
# --clean 逻辑
# ──────────────────────────────────────────────


def cmd_clean(project_root: Path) -> int:
    """删除所有引擎层文件，项目恢复纯净状态。"""
    cleaned: list[str] = []

    for target in CLEAN_TARGETS:
        path = project_root / target
        if not path.exists():
            continue
        if path.is_dir():
            shutil.rmtree(path, ignore_errors=True)
        else:
            path.unlink(missing_ok=True)
        cleaned.append(target)
        logger.info("Cleaned: %s", target)

    if cleaned:
        print(f"[CLEAN] Removed: {', '.join(cleaned)}")
        print("[CLEAN] Project restored to pure development state (nodes/ untouched).")
    else:
        print("[CLEAN] Nothing to clean — no engine files found.")
    return 0


# ──────────────────────────────────────────────
# 主 build 函数
# ──────────────────────────────────────────────


def cmd_build(
    project_root: Path,
    force: bool = False,
    docker: bool = False,
    update: bool = False,
) -> int:
    """bnos build — 注入运行时引擎到当前项目。"""
    # 1. 验证项目
    if not (project_root / "nodes").is_dir():
        print("[ERROR] Not a BNOS project: no nodes/ directory")
        return 1

    canvas_layout_path = project_root / "canvas_layout.json"
    if not canvas_layout_path.exists():
        print("[ERROR] No canvas_layout.json found. Open the project in BNOS Studio first.")
        return 1

    runtime_dir = project_root / "bnos_runtime"
    pipeline_path = project_root / "pipeline.json"

    # 2. 检查已有引擎
    if runtime_dir.exists() and not force and not update:
        print("[ERROR] bnos_runtime/ already exists. Use --force to overwrite or --update to refresh.")
        return 1

    # 3. 读取画布状态
    print("[BUILD] Reading canvas state...")
    with open(canvas_layout_path, encoding="utf-8") as f:
        canvas_layout = json.load(f)

    node_clusters: dict = {}
    clusters_path = project_root / "node_clusters.json"
    if clusters_path.exists():
        with open(clusters_path, encoding="utf-8") as f:
            node_clusters = json.load(f)

    # 4. 生成 pipeline.json
    print("[BUILD] Generating pipeline.json from canvas state...")
    pipeline = generate_pipeline(project_root, pipeline_path, canvas_layout, node_clusters)

    # 4a. 验证 pipeline
    errors = validate_pipeline(pipeline, project_root)
    if errors:
        for e in errors:
            print(f"  {e}")
        if any("[FATAL]" in e for e in errors):
            print("[ERROR] Pipeline validation failed. Aborting.")
            return 1

    standalone_count = sum(1 for n in pipeline["nodes"].values() if n["type"] == "standalone")
    composite_count = sum(1 for n in pipeline["nodes"].values() if n["type"] == "composite")
    print(f"  [OK] {len(pipeline['nodes'])} nodes ({standalone_count} standalone, {composite_count} composite)")
    print(f"  [OK] {len(pipeline['edges'])} edges")

    # 5. 注入引擎核心文件（仅在首次或 --force 时）
    if not update:
        print("[BUILD] Injecting runtime engine...")
        inject_runtime_engine(runtime_dir)
        py_files = list(runtime_dir.rglob("*.py"))
        print(f"  [OK] {len(py_files)} modules written")

    # 6. 生成复合节点 orchestrator
    for node_name, node_def in pipeline["nodes"].items():
        if node_def["type"] == "composite":
            orch_path = project_root / node_def["path"] / "orchestrator.py"
            generate_orchestrator(orch_path, node_def, project_root)
            print(f"  [OK] orchestrator.py → {orch_path}")

    # 7. 生成 requirements.txt
    reqs = scan_requirements(project_root, pipeline["nodes"])
    reqs_path = project_root / "requirements.txt"
    with open(reqs_path, "w", encoding="utf-8") as f:
        f.write("# BNOS Runtime dependencies (no PySide6)\n")
        for req in sorted(reqs):
            f.write(f"{req}\n")
    print(f"  [OK] requirements.txt ({len(reqs)} packages)")

    # 8. 生成启动脚本
    generate_run_scripts(project_root)
    print("  [OK] run.sh + run.bat")

    # 9. 可选：Docker
    if docker:
        generate_docker_files(project_root)
        print("  [OK] Dockerfile + docker-compose.yml + .dockerignore")

    # 10. 构建报告
    print()
    print("=" * 50)
    print(f"[BUILD] Success! Pipeline '{pipeline['name']}' is ready.")
    print(f"[BUILD] Run: cd {project_root} && python -m bnos_runtime.engine pipeline.json")
    if update:
        print("[BUILD] (--update mode: pipeline.json regenerated, engine core unchanged)")
    return 0


# ──────────────────────────────────────────────
# Docker 文件生成
# ──────────────────────────────────────────────


def generate_docker_files(project_root: Path) -> None:
    """生成 Dockerfile + .dockerignore + docker-compose.yml。"""
    # Dockerfile
    dockerfile = project_root / "Dockerfile"
    dockerfile.write_text(
        "FROM python:3.12-slim\n"
        "\n"
        "WORKDIR /app\n"
        "\n"
        "COPY requirements.txt .\n"
        "RUN pip install --no-cache-dir -r requirements.txt\n"
        "\n"
        "COPY . .\n"
        "\n"
        'CMD ["python", "-m", "bnos_runtime.engine", "pipeline.json"]\n',
        encoding="utf-8",
    )

    # .dockerignore
    dockerignore = project_root / ".dockerignore"
    dockerignore.write_text(
        "ui/canvas/\n"
        "ui/panels/\n"
        "ui/dialogs/\n"
        "ui/main_window/\n"
        "ui/creators/\n"
        "ui/icons/\n"
        ".dockerignore\n"
        "Dockerfile\n"
        "*.md\n"
        ".git/\n"
        "__pycache__/\n"
        "*.pyc\n",
        encoding="utf-8",
    )

    # docker-compose.yml
    compose = project_root / "docker-compose.yml"
    compose.write_text(
        'version: "3.8"\n'
        "services:\n"
        f"  {project_root.name}:\n"
        "    build: .\n"
        "    restart: on-failure\n"
        "    environment:\n"
        "      - BNOS_LOG_LEVEL=INFO\n"
        "    volumes:\n"
        "      - ./output:/app/output\n"
        "    deploy:\n"
        "      resources:\n"
        "        limits:\n"
        "          memory: 2G\n"
        "          cpus: \"2\"\n",
        encoding="utf-8",
    )


# ──────────────────────────────────────────────
# 参数解析
# ──────────────────────────────────────────────


def register_args(subparsers) -> None:
    """注册 bnos build 子命令到 argparse 子解析器。"""
    parser = subparsers.add_parser("build", help="注入运行时驱动引擎到当前项目")
    parser.add_argument(
        "--docker", action="store_true",
        help="同时生成 Dockerfile + docker-compose.yml",
    )
    parser.add_argument(
        "--force", action="store_true",
        help="覆盖已有 bnos_runtime/、pipeline.json 等文件",
    )
    parser.add_argument(
        "--clean", action="store_true",
        help="仅删除引擎文件（bnos_runtime/、pipeline.json、run.*），不碰 nodes/",
    )
    parser.add_argument(
        "--update", action="store_true",
        help="更新 pipeline.json + 复合节点编排器（引擎核心不动）",
    )
    parser.set_defaults(func=cmd_build_wrapper)


def cmd_build_wrapper(args) -> int:
    """CLI 入口包装器。"""
    project_root = Path.cwd()
    if args.clean:
        return cmd_clean(project_root)
    return cmd_build(
        project_root=project_root,
        force=args.force,
        docker=args.docker,
        update=args.update,
    )


def main():
    """独立 CLI 入口。"""
    parser = argparse.ArgumentParser(
        prog="bnos build",
        description="BNOS Build — 注入运行时驱动引擎到当前项目",
    )
    parser.add_argument(
        "--docker", action="store_true",
        help="同时生成 Docker 支持文件",
    )
    parser.add_argument(
        "--force", action="store_true",
        help="覆盖已有引擎",
    )
    parser.add_argument(
        "--clean", action="store_true",
        help="移除引擎文件",
    )
    parser.add_argument(
        "--update", action="store_true",
        help="仅更新 pipeline.json + 编排器",
    )
    args = parser.parse_args()

    if args.clean:
        return cmd_clean(Path.cwd())
    return cmd_build(
        project_root=Path.cwd(),
        force=args.force,
        docker=args.docker,
        update=args.update,
    )


if __name__ == "__main__":
    sys.exit(main())
